galaxy:
  num_stars:
    dist: poisson
    mean: 100

dm_potential:
  type: Spheroid
  parameters:
    - name: alpha
      dist: delta
      value: 1
    - name: beta
      dist: delta
      value: 3
    - name: gamma  # the inner slope
      dist: uniform
      min: -1
      max: 2
    - name: r_dm  # the DM scale radius in kpc
      dist: log_uniform
      min: 0.1
      max: 10
    - name: rho_0  # the density normalization in Msun / kpc^3
      dist: log_uniform
      min: 1.0e+5
      max: 1.0e+8
    - name: p  # axis ratio between the Y and X axis
      dist: uniform
      min: 0.8
      max: 1.0
    - name: q  # axis ratio between the Z and X axis
      dist: delta
      value: 1.0

stellar_density:
  type: Spheroid  # triaxial Plummer
  parameters:
    # set slope similar to Plummer
    - name: alpha
      dist: delta
      value: 2
    - name: beta
      dist: delta
      value: 5
    - name: gamma
      dist: delta
      value: 0
    - name: r_star_r_dm  # ratio of Plummer scale radius to DM scale radius
      dist: uniform
      min: 0.2
      max: 1.0
    - name: rho_0  # density normalization in Msun / kpc^3, set to small number
      dist: delta
      value: 1
    - name: p  # axis ratio between the Y and X axis
      dist: uniform
      min: 0.8
      max: 1.0
    - name: q  # axis ratio between the Z and X axis
      dist: delta
      value: 1.0

distribution_function:
  type: QuasiSpherical  # Osipkov-Merrit velocity anisotropy
  parameters:
    - name: beta_0  # normalization for the OM velocity anistropy profile
      dist: uniform
      min: -0.5
      max: 0.5
    - name: r_a_r_star
      dist: uniform
      min: 0.5
      max: 2