model_name: GraphRegressor
model_params:
  activation: leaky_relu
  activation_params:
    negative_slope: 0.01
  flow_params:
    activation: tanh
    hidden_channels: 128
    num_blocks: 2
    num_layers: 4
  graph_layer_name: ChebConv
  graph_layer_params:
    K: 4
    bias: true
    normalization: sym
  hidden_fc_channels: 128
  hidden_graph_channels: 128
  in_channels: 2
  num_fc_layers: 2
  num_graph_layers: 4
  out_channels: 5
optimizer_params:
  betas:
  - 0.9
  - 0.999
  lr: 0.0005
  type: AdamW
  weight_decay: 0.01
pre_transform_params: {}
run_name: gnfw_beta_priorlarge_pois100_cheb-small
run_prefix: /mnt/ceph/users/tnguyen/jeans_gnn/trained_models
scheduler_params:
  factor: 0.5
  interval: epoch
  patience: 10
  type: ReduceLROnPlateau
transform_params:
  graph_name: KNNGraph
  graph_params:
    k: 20
    loop: true
  log_radius: true
  use_vel_error: false
